[WIP] karma: Add karma test to test-project run
thheller/shadow-cljs pull request #815
Opened 2020-12-29 21:27 UTC by palfrey

2021-01-04 10:15 UTC, thheller requested changes

2021-01-12 18:25 UTC, palfrey commented on test-project/ci-run.sh
> +CHROME_BIN=/usr/bin/chromium npx karma start --single-run
That's going to be a little tricky, given this script runs in `thheller/cljs-dev` and I'm not seeing the source for that anywhere?

2021-01-12 20:22 UTC, thheller commented on test-project/ci-run.sh
> +CHROME_BIN=/usr/bin/chromium npx karma start --single-run
Well happy to take any other image that has all the stuff needed installed. I can't even remember how I created that image. Could probably use an update on that one too.

Just needs java, lein, node, npm.

2021-01-27 23:33 UTC, palfrey commented on test-project/ci-run.sh
> +CHROME_BIN=/usr/bin/chromium npx karma start --single-run
Turns out CircleCI provide some pretty decent images these days, and one of those fits the bill. Fixed!

2021-05-06 21:16 UTC, palfrey commented on test-project/ci-run.sh
> +CHROME_BIN=/usr/bin/chromium npx karma start --single-run
Any further thoughts on this @thheller?

2021-06-07 19:38 UTC, thheller approved these changes

2021-06-07 19:39 UTC, thheller commented
Sorry for sitting so long on this. I'm really not a fan of karma but I guess it makes sense given that other people use it.

2021-06-07 19:39 UTC, merged